### ISSUE TITLE
Cannot Generate JSON with RM4 Mini

### ISSUE THREAD

**Issue by Nanianmichaels** [gpongelli/broadlink-listener#7]
* Broadlink Listener version: 1.2.0
* Python version: 3.11.3
* Operating System: Windows 11

### Description

I am trying to create a json for a series of Mitsubishi AC units that are not yet supported by SmartIR.

After A LOT of fiddling with the JSON (I'm very much of a noob with anything even remotely resembling programming, so it took me a good 1.5+ hours to figure out that "{" is different than "[", and that I was missing a "}" at the end of the file, and to create a fully-fledged JSON with all the options. Luckily, an online JSON debugger helped.

After parsing everything to the command line, I am left with a "Controller not supported" message.

### What I Did

```
Command run:
`broadlink-listener generate-smart-ir T7WE10714.json 0x653a 192.168.2.xx a043b070xxxx -n fan_only`

(IP and MAC partially masked). Controller type gotten by running `broadlink-listener discover-ir`.

Output:
`Error: Controller ['Broadlink'] not supported`
```

This is a RM4MINI unit, and AFAIK it has learning capabilities, which have been added to python-broadlink, so I'm at a loss of what I'm doing wrong, or what's missing from my setup.

Any help appreciated, and I'm available to test.

Thank you for your time, and for the help.

**Comment by gpongelli** [comment]
Hi, sorry for this late response.

have you previously run the discover command ? if so, which is the output ?

**Comment by Nanianmichaels** [comment]
Hello.

I have since stopped using both the Mitsubishi AC units, the RM4Mini, and Windows, so I can't reproduce this issue anymore.

I'll close it, had forgotten it was still open.
