### ISSUE TITLE
discover-ir on a differenet subnet

### ISSUE THREAD

**Issue by ghost** [gpongelli/broadlink-listener#8]
* Broadlink Listener version: v1.2.0
* Python version: 3.9.2
* Operating System: Debian Bullseye

### Description

Trying to run discover-ir on a Broadlink device residing on a different subnet. Nothing discovered. Is it possible to make it work? I'm guessing the tool is just trying to find devices on the same subnet as itself.

### What I Did

```
broadlink-listener discover-ir xxx.xxx.xxx.xxx
```

**Comment by gpongelli** [comment]
Hi,
sorry for this late response.

That constraint comes from broadlink python package, used by this one. The ip address you put there is [directly passed to that package](https://github.com/gpongelli/broadlink-listener/blob/main/broadlink_listener/cli_tools/cli.py#L74).

Sorry but it's not possible to solve your issue in this package, try open an issue on that package.
